[package]
name = "config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
toml.workspace = true
serde.workspace = true
thiserror.workspace = true
